#Deployment configuration main
#https://www.linuxtechi.com/install-kubernetes-1-7-centos7-rhel7/

- name: K8s Deployment configuration for master
  gather_facts: true
  become: true
  hosts: all

- hosts: masters
  become: true
  gather_facts: false
  roles:
    - role: common
    - role: master
  tags: masters
#kubectl get no -n kube-system

- hosts: workers
  become: true
  gather_facts: false
  roles:
    - role: common
    - role: workers
  tags: workers
