apiVersion: v1
 kind: Pod
 metadata:
   labels:
       component: etcd
       tier: control-plane
   name: etcd
   namespace: kube-system
 spec:
   containers:
   - command:
       etcd --name master-1 \
       --data-dir /var/lib/etcd \
       --listen-client-urls https://0.0.0.0:2379 \
       --advertise-client-urls https://{{ hostvars[inventory_hostname]['ansible_ens33']['ipv4']['address'] }}:2379 \
       --listen-peer-urls http://0.0.0.0:2380 \
       --initial-advertise-peer-urls https://{{ hostvars[inventory_hostname]['ansible_ens33']['ipv4']['address'] }}:2380 \
       --cert-file=/certs/server.pem \
       --key-file=/certs/server-key.pem \
       --client-cert-auth \
       --trusted-ca-file=/certs/ca.pem \
       --peer-cert-file=/certs/peer.pem \
       --peer-key-file=/certs/peer-key.pem \
       --peer-client-cert-auth \
       --peer-trusted-ca-file=/certs/ca.pem \
       --initial-cluster etcd0=https://{{ hostvars[groups['masters'][0]]['ansible_ens33']['ipv4']['address'] }}:2380,etcd1=https://{{ hostvars[groups['masters'][1]]['ansible_ens33']['ipv4']['address'] }}:2380,etcd2=https://{{ hostvars[groups['masters'][1]]['ansible_ens33']['ipv4']['address'] }}:2380 \
       --initial-cluster-token etcd-token \
       --initial-cluster-state new
       image: gcr.io/google_containers/etcd-amd64:3.2.15
       resources:
          limits:
            cpu: "1000m"
            memory: "256Mi"
       ports:
          - name: client
            containerPort: 2379
            protocol: "TCP"
          - name: peer
            containerPort: 2380
            protocol: "TCP"
       httpGet:
           path: /health
           port: 2379
           scheme: HTTP
       initialDelaySeconds: 15
       timeoutSeconds: 15
       name: etcd
       volumeMounts:
         - mountPath: /var/lib/etcd
           name: etcd
         - mountPath: /certs
           name: certs
   hostNetwork: true
   volumes:
   - hostPath:
       path: /var/lib/etcd
       type: DirectoryOrCreate
       name: etcd
   - hostPath:
       path: /etc/kubernetes/pki/etcd
       name: certs
